{
    'name': 'Meta Lead Ads CRM Connector',
    'version': '19.0.3.1.0',
    'summary': 'Real-time Meta Facebook/Instagram Lead Ads integration for Odoo CRM',
    'category': 'Sales/CRM',
    'author': 'Andrew Raof',
    'license': 'LGPL-3',
    'depends': ['base', 'crm', 'utm', 'mail'],
    'data': [
        'security/meta_security.xml',
        'security/ir.model.access.csv',
        'data/utm_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_cron_update.xml',
        'views/meta_account_views.xml',
        'views/meta_page_views.xml',
        'views/meta_form_views.xml',
        'views/meta_lead_queue_views.xml',
        'views/meta_lead_log_views.xml',
        'views/meta_message_views.xml',
        'views/meta_conversation_views.xml',
        'views/crm_lead_views.xml',
        'views/res_config_settings_views.xml',
        'views/meta_menus.xml',
    ],
    'installable': True,
    'application': False,
}
